### ISSUE TITLE
game crashes when searching for deck in JEI

### ISSUE THREAD

**Issue by luque7a** [vemerion/Minecard#1]
[crash-2023-07-02_19.50.37-client.txt](https://github.com/vemerion/Minecard/files/12553584/crash-2023-07-02_19.50.37-client.txt)

**Comment by vemerion** [comment]
The log is for Fabric 1.20 (seems like the continuity mod is causing the crash?), but Minecard is a 1.18 Forge mod. Will close this ticket.
